version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/LysaghtMalaysia
permissions:
   - object: /var/www/html/LysaghtMalaysia
     pattern: "**"
     owner: root
     group: root
     mode: 755
     overwrite: yes
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/installapache.sh
      runas: root